<?php
/**
 * Copyright © 2017 PersonaClick. All rights reserved.
 */
?>
<div id="personaclick_auth_block" style="display: none;">
    <div class="admin__control-table-wrapper">
        <table class="admin__control-table">
            <tr>
                <td style="text-align: center;">
                    <button type="button" class="action-secondary" id="personaclick_login_button"><span><?php echo __('Authorize'); ?></span></button>
                </td>
                <td style="text-align: center;">
                    <button type="button" class="action-secondary" id="personaclick_register_button"><span><?php echo __('Register'); ?></span></button>
                </td>
            </tr>
        </table>
    </div>
</div>
