<?php
/**
 * Copyright © 2017 PersonaClick. All rights reserved.
 */
?>
<style>
#personaclick_auth_block + .section-config, #personaclick_auth_block + div + .section-config {
    display: none;
}
.personaclick-enabled-icon:before {
    font-family: 'Admin Icons';
    font-size: 1.5rem;
    color: #79a22e;
    content: '\e62d';
}
.personaclick-disabled-icon:before {
    font-family: 'Admin Icons';
    font-size: 1.5rem;
    color: #a79d95;
    content: '\e62f';
}
</style>